
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Sep 12 16:33:01 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 47;
  public static final int MAP = 18;
  public static final int INCREMENT = 34;
  public static final int CONST = 7;
  public static final int SLASH = 23;
  public static final int CLOSED_BRACE = 45;
  public static final int NOT_EQUAL = 26;
  public static final int LOWER = 29;
  public static final int CONTINUE = 14;
  public static final int INTERFACE = 19;
  public static final int HIGHER_EQUAL = 28;
  public static final int DECREMENT = 35;
  public static final int MINUS = 21;
  public static final int STAR = 22;
  public static final int SEMICOLON = 36;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int COMMA = 38;
  public static final int CLASS = 4;
  public static final int PLUS = 20;
  public static final int ASSIGN = 33;
  public static final int IF = 5;
  public static final int DOT = 39;
  public static final int EOF = 0;
  public static final int RETURN = 11;
  public static final int EQUAL = 25;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int OPEN_BRACE = 44;
  public static final int HIGHER = 27;
  public static final int IDENT = 49;
  public static final int OPEN_BRACKET = 42;
  public static final int BREAK = 3;
  public static final int VOID = 12;
  public static final int OPEN_PARENTHESIS = 40;
  public static final int COLON = 37;
  public static final int UNION = 15;
  public static final int ELSE = 6;
  public static final int CLOSED_PARENTHESIS = 41;
  public static final int READ = 10;
  public static final int WHILE = 17;
  public static final int CLOSED_BRACKET = 43;
  public static final int LOWER_EQUAL = 30;
  public static final int EXTENDS = 13;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 46;
  public static final int PERCENTAGE = 24;
  public static final int PRINT = 9;
  public static final int DO = 16;
  public static final int NUMBER_CONST = 48;
}

